
# Notes ________________________________________
# ...
#_______________________________________________

case_index        : 0      # used for backup name
Stage             : 1       # 0: Only sparse reconstruction 1: Only temporal propagation -1: Train both together
Repeat_id         : 0       # Different propagator id sharing the same encoder and decoder

data_h5           : 2D_CollinearPlateFlow/Dataset/processed/Data2PlatesGap1Re40.h5

# data ----------------------------------------------------
Spatial_Dim       : 2          # Spatial dimension: 1, 2 or 3
delta_t           : 0.001      
U_dim             : 1          # Dummy in this case

N_window          : 2
num_time_sample   : 4          # N_ts, for encoder to generate latent trajectory
num_space_sample  : 64         # N_xs, spatial points randomly sampled
multi_factor      : 1

num_workers       : 8
train_ratio       : 0.90
batch_size        : 128
num_samples       : 1024           # Resample in one case
Full_Field_DownS  : 0.25            # Downsampling ratio for reconstruction in training

channel           : 0               # Choose between 0, 1,...-1. For channel =-1 the code load all fields
process_mode      : MeanStdStand    # Choose between MinMaxNorm, MeanStdStand, SymLogQuant and None

global_restriction     : False         # Determine if we restrict the whole reconstruction area
sample_restriction     : False         # Determine if we restrict the sampling area
Sample_Parameters:                    # Regions that we limit sampling
  x_lo              : -1.0
  x_hi              : 1.0
  y_lo              : -1.0
  y_hi              : 1.0

# Modify based on data structure
Num_x             : 88
Num_y             : 300

# model ---------------------------------------------------

F_dim             : 32
num_heads         : 16
num_layers        : 4
num_layers_block  : 6
num_layers_propagator : 2

latent_tokens     : 128             # For cross-att in perceiver reconstructor
latent_size       : 1

# training -----------------------------------------------
num_epochs        : 100000

learning_rate     : 3.0e-4
weight_decay      : 1.0e-6       # Weight decay for AdamW
warmup_epochs     : 50
monitor_every     : 5
patience_epochs   : 5000
Loss_Traj_Weight  : 1.0

Reload_Trained    : False
CheckPhi          : false

# folders -------------------------------------------------
save_loss_dir     : Save_loss_files/collinear_flow_Re40/train_test_loss_Senseiver
save_net_dir      : Output_Net/collinear_flow_Re40/Net_Senseiver
save_recon_dir    : Save_reconstruction_files/collinear_flow_Re40/Results_Senseiver